// <auto-generated />
using System;
using IjarifySystemDAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IjarifySystemDAL.Migrations
{
    [DbContext(typeof(IjarifyDbContext))]
    [Migration("20260213121025_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmenityProperty", b =>
                {
                    b.Property<int>("amenitiesId")
                        .HasColumnType("int");

                    b.Property<int>("propertiesId")
                        .HasColumnType("int");

                    b.HasKey("amenitiesId", "propertiesId");

                    b.HasIndex("propertiesId");

                    b.ToTable("AmenityProperty");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Interior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "wifi",
                            Name = "WiFi"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Interior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "snowflake",
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Exterior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "car",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Exterior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "water",
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Interior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "dumbbell",
                            Name = "Gym"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Exterior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "shield",
                            Name = "Security"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Interior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "elevator",
                            Name = "Elevator"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Exterior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "tree",
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Exterior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "balcony",
                            Name = "Balcony"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Interior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "fire",
                            Name = "Central Heating"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Interior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "kitchen",
                            Name = "Kitchen Appliances"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Interior",
                            CreatedAt = new DateTime(2024, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "couch",
                            Name = "Furnished"
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Check_In")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Check_Out")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyID");

                    b.HasIndex("UserID");

                    b.ToTable("bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Check_In = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Check_Out = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 2, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyID = 1,
                            Status = "Approved",
                            TotalPrice = 15000m,
                            UserID = 2
                        },
                        new
                        {
                            Id = 2,
                            Check_In = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Check_Out = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 3, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            PropertyID = 2,
                            Status = "Approved",
                            TotalPrice = 25000m,
                            UserID = 4
                        },
                        new
                        {
                            Id = 3,
                            Check_In = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Check_Out = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 3, 5, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            PropertyID = 3,
                            Status = "Pending",
                            TotalPrice = 8000m,
                            UserID = 2
                        },
                        new
                        {
                            Id = 4,
                            Check_In = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Check_Out = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            PropertyID = 5,
                            Status = "Rejected",
                            TotalPrice = 8000m,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("favourites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 28, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 20, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 25, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 28, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 7,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("varchar");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Inquiries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Message = "Is the apartment still available for rent starting next month? Also, are pets allowed?",
                            PropertyId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 10, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Message = "I'm interested in renting the villa for the summer. Can we schedule a viewing?",
                            PropertyId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 15, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Message = "Does the rent include utilities? Also, is there parking available?",
                            PropertyId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "What is the minimum lease period for the office space?",
                            PropertyId = 7,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Regoin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New Cairo",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://prod-images.nawy.com/processed/area/image/2/high.webp",
                            Latitude = 30.0055m,
                            Longitude = 31.4782m,
                            Regoin = "Fifth Settlement",
                            Street = "North 90th St"
                        },
                        new
                        {
                            Id = 2,
                            City = "New Capital City",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
                            Latitude = 30.0131m,
                            Longitude = 31.7258m,
                            Regoin = "R7 District",
                            Street = "Bin Zayed Axis"
                        },
                        new
                        {
                            Id = 3,
                            City = "6th October City",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://prod-images.nawy.com/processed/area/image/1/high.webp",
                            Latitude = 29.9737m,
                            Longitude = 30.9510m,
                            Regoin = "West Somid",
                            Street = "26th of July Corridor"
                        },
                        new
                        {
                            Id = 4,
                            City = "Mostakbal City",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://prod-images.nawy.com/processed/area/image/10/high.webp",
                            Latitude = 30.1290m,
                            Longitude = 31.6030m,
                            Regoin = "Phase 1",
                            Street = "Suez Road"
                        },
                        new
                        {
                            Id = 5,
                            City = "El Gouna",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://prod-images.nawy.com/processed/area/image/5/high.webp",
                            Latitude = 27.3942m,
                            Longitude = 33.6782m,
                            Regoin = "Abu Tig Marina",
                            Street = "Marina Way"
                        },
                        new
                        {
                            Id = 6,
                            City = "El Shorouk",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
                            Latitude = 30.1197m,
                            Longitude = 31.6046m,
                            Regoin = "District 3",
                            Street = "El Horreya Axis"
                        },
                        new
                        {
                            Id = 7,
                            City = "Maadi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://cairogossip.com/app/uploads/2020/02/caf268d7b5e3978ce944d44b6a144653.jpg",
                            Latitude = 29.9599m,
                            Longitude = 31.2676m,
                            Regoin = "Degla",
                            Street = "Road 233"
                        },
                        new
                        {
                            Id = 8,
                            City = "Ain Sokhna",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.etbtoursegypt.com/storage/1421/Ain-El-Sokhna-Travel-Guide.jpg",
                            Latitude = 29.5768m,
                            Longitude = 32.3385m,
                            Regoin = "Galala",
                            Street = "Zaafarana Road"
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3732),
                            DiscountPercentage = 10m,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 1,
                            Title = "Spring Special - 10% Off"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3865),
                            DiscountPercentage = 10m,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 2,
                            Title = "Ramadan Mubarak Deal"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3880),
                            DiscountPercentage = 10m,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 3,
                            Title = "Spring Special - 10% Off"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3890),
                            DiscountPercentage = 10m,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 4,
                            Title = "Summer Early Bird"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3900),
                            DiscountPercentage = 15m,
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 5,
                            Title = "Ramadan Offer"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3910),
                            DiscountPercentage = 5m,
                            EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 7,
                            Title = "Summer Early Bird"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3919),
                            DiscountPercentage = 20m,
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 6,
                            Title = "Eid Sale - Villas"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3929),
                            DiscountPercentage = 12m,
                            EndDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            PropertyId = 5,
                            Title = "Office Lease Discount"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3939),
                            DiscountPercentage = 12m,
                            EndDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            PropertyId = 8,
                            Title = "Family Home Promo"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3948),
                            DiscountPercentage = 5m,
                            EndDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 1,
                            Title = "Weekend Getaway"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3958),
                            DiscountPercentage = 25m,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 2,
                            Title = "Monthly Stay Discount"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3968),
                            DiscountPercentage = 8m,
                            EndDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 3,
                            Title = "Business Trip Special"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3977),
                            DiscountPercentage = 30m,
                            EndDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 4,
                            Title = "Last Minute Deal"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3989),
                            DiscountPercentage = 15m,
                            EndDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 5,
                            Title = "Winter Escape"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(3999),
                            DiscountPercentage = 20m,
                            EndDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 6,
                            Title = "New Year Bash"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4009),
                            DiscountPercentage = 12m,
                            EndDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 7,
                            Title = "Student Housing Promo"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4018),
                            DiscountPercentage = 10m,
                            EndDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 8,
                            Title = "Loyalty Reward"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4028),
                            DiscountPercentage = 18m,
                            EndDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 1,
                            Title = "Honeymoon Suite Deal"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4037),
                            DiscountPercentage = 40m,
                            EndDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 2,
                            Title = "Flash Sale 24h"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4047),
                            DiscountPercentage = 7m,
                            EndDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 3,
                            Title = "Autumn Leaves Discount"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4057),
                            DiscountPercentage = 9m,
                            EndDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 4,
                            Title = "Cozy Apartment Deal"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4066),
                            DiscountPercentage = 22m,
                            EndDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 5,
                            Title = "Corporate Booking"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4076),
                            DiscountPercentage = 11m,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 6,
                            Title = "Beachfront Special"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4085),
                            DiscountPercentage = 35m,
                            EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 7,
                            Title = "Long Term Lease"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4155),
                            DiscountPercentage = 14m,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 8,
                            Title = "Referral Bonus"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4186),
                            DiscountPercentage = 16m,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 1,
                            Title = "Summer Solstice"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4198),
                            DiscountPercentage = 13m,
                            EndDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 2,
                            Title = "Back to School"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4208),
                            DiscountPercentage = 50m,
                            EndDate = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 3,
                            Title = "Black Friday Rental"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 2, 13, 14, 10, 23, 512, DateTimeKind.Local).AddTicks(4218),
                            DiscountPercentage = 20m,
                            EndDate = new DateTime(2026, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 4,
                            Title = "Christmas Spirit"
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BathRooms")
                        .HasColumnType("int");

                    b.Property<int>("BedRooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("varchar");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Properties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 150m,
                            BathRooms = 2,
                            BedRooms = 3,
                            CreatedAt = new DateTime(2024, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spacious 3-bedroom apartment with modern amenities and stunning city views. Perfect for families looking for comfort and convenience in the heart of Nasr City.",
                            ListingType = "Rent",
                            LocationId = 1,
                            Price = 15000m,
                            Title = "Luxury Apartment in Nasr City",
                            Type = "Apartment",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Area = 350m,
                            BathRooms = 4,
                            BedRooms = 5,
                            CreatedAt = new DateTime(2024, 1, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beautiful villa with private beach access, pool, and garden. Ideal for vacation rentals or permanent residence. Enjoy the Mediterranean lifestyle.",
                            ListingType = "Rent",
                            LocationId = 2,
                            Price = 50000m,
                            Title = "Beachfront Villa in Alexandria",
                            Type = "Villa",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Area = 60m,
                            BathRooms = 1,
                            BedRooms = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cozy studio apartment in the heart of Zamalek, close to cafes, restaurants, and shops. Perfect for young professionals.",
                            ListingType = "Rent",
                            LocationId = 3,
                            Price = 8000m,
                            Title = "Modern Studio in Zamalek",
                            Type = "Studio",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Area = 280m,
                            BathRooms = 3,
                            BedRooms = 4,
                            CreatedAt = new DateTime(2024, 2, 10, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spacious family townhouse with garden, 4 bedrooms, and modern kitchen. Located in a quiet compound with 24/7 security.",
                            ListingType = "Rent",
                            LocationId = 4,
                            Price = 25000m,
                            Title = "Family Townhouse in 6th October",
                            Type = "Townhouse",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Area = 250m,
                            BathRooms = 3,
                            BedRooms = 4,
                            CreatedAt = new DateTime(2024, 2, 15, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luxurious penthouse with panoramic views, private terrace, and premium finishes. Features include smart home system and private parking.",
                            ListingType = "Rent",
                            LocationId = 5,
                            Price = 35000m,
                            Title = "Penthouse Apartment in New Cairo",
                            Type = "Apartment",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Area = 100m,
                            BathRooms = 1,
                            BedRooms = 2,
                            CreatedAt = new DateTime(2024, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Well-maintained 2-bedroom apartment, perfect for small families or couples. Close to schools and shopping centers.",
                            ListingType = "Rent",
                            LocationId = 1,
                            Price = 10000m,
                            Title = "Affordable Apartment in Nasr City",
                            Type = "Apartment",
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            Area = 200m,
                            BathRooms = 2,
                            BedRooms = 0,
                            CreatedAt = new DateTime(2024, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prime office location in downtown Cairo with modern facilities and easy access to public transportation.",
                            ListingType = "Rent",
                            LocationId = 8,
                            Price = 40000m,
                            Title = "Commercial Office Space in Downtown Cairo",
                            Type = "Office",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Area = 180m,
                            BathRooms = 3,
                            BedRooms = 0,
                            CreatedAt = new DateTime(2024, 2, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fully equipped medical clinic with modern equipment and established patient base. Great investment opportunity.",
                            ListingType = "Sale",
                            LocationId = 7,
                            Price = 2500000m,
                            Title = "Medical Clinic for Sale in Nasr City",
                            Type = "Clinic",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.PropertyImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
                            PropertyId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800",
                            PropertyId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 2, 10, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
                            PropertyId = 4
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 2, 10, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
                            PropertyId = 4
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 2, 10, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800",
                            PropertyId = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 2, 15, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
                            PropertyId = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 2, 15, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800",
                            PropertyId = 5
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 2, 15, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800",
                            PropertyId = 5
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800",
                            PropertyId = 6
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1560185009-5bf9f2849488?w=800",
                            PropertyId = 6
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
                            PropertyId = 7
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
                            PropertyId = 7
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 2, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800",
                            PropertyId = 8
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 2, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1551076805-e1869033e561?w=800",
                            PropertyId = 8
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating_Range", "Rating Between 1 and 10");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Amazing apartment! Very spacious and clean. The location is perfect and the landlord is very responsive.",
                            CreatedAt = new DateTime(2024, 2, 5, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 1,
                            Rating = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Dream villa! The beach access is incredible and the kids love the pool. Highly recommended!",
                            CreatedAt = new DateTime(2024, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 2,
                            Rating = 10,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Nice studio in a great location. Perfect for my needs as a single professional.",
                            CreatedAt = new DateTime(2024, 2, 25, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 3,
                            Rating = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Excellent family townhouse. The compound is safe and the neighbors are friendly. Kids love playing in the garden.",
                            CreatedAt = new DateTime(2024, 3, 5, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 4,
                            Rating = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Good apartment for the price. Could use some updates but overall a solid choice.",
                            CreatedAt = new DateTime(2024, 3, 15, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 6,
                            Rating = 7,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_IjarifyUserValidEmail", "Email like '_%@_%._%'");

                            t.HasCheckConstraint("CK_IjarifyUserValidPhone", "PhoneNumber like '01%' and PhoneNumber not like '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "cairo",
                            ConcurrencyStamp = "afa309ab-5a3d-411e-b5d0-be54efe269d3",
                            CreatedAt = new DateTime(2024, 1, 20, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.ali@example.com",
                            EmailConfirmed = false,
                            ImageUrl = "https://i.pravatar.cc/150?img=33",
                            LockoutEnabled = false,
                            Name = "Omar Ali",
                            PasswordHash = "AQAAAAEAACcQAAAAEH8zQK",
                            PhoneNumber = "01234567890",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "cairo",
                            ConcurrencyStamp = "9412d4c6-d315-4666-8954-fde88d6cd97a",
                            CreatedAt = new DateTime(2024, 3, 5, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.ibrahim@example.com",
                            EmailConfirmed = false,
                            ImageUrl = "https://i.pravatar.cc/150?img=27",
                            LockoutEnabled = false,
                            Name = "Nour Ibrahim",
                            PasswordHash = "AQAAAAEAACcQAAAAEH8zQK",
                            PhoneNumber = "01098765432",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "cairo",
                            ConcurrencyStamp = "edcabd7c-3ad7-4bfb-9ced-5088d9db0e2d",
                            CreatedAt = new DateTime(2024, 2, 28, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled.mahmoud@example.com",
                            EmailConfirmed = false,
                            ImageUrl = "https://i.pravatar.cc/150?img=51",
                            LockoutEnabled = false,
                            Name = "Khaled Mahmoud",
                            PasswordHash = "AQAAAAEAACcQAAAAEH8zQK",
                            PhoneNumber = "01187654321",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "cairo",
                            ConcurrencyStamp = "a6a0a156-320c-472a-9522-12a15129f30b",
                            CreatedAt = new DateTime(2024, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.hassan@example.com",
                            EmailConfirmed = false,
                            ImageUrl = "https://i.pravatar.cc/150?img=12",
                            LockoutEnabled = false,
                            Name = "Ahmed Hassan",
                            PasswordHash = "AQAAAAEAACcQAAAAEH8zQK",
                            PhoneNumber = "01012345678",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "cairo",
                            ConcurrencyStamp = "2e6b3f20-ffad-46ec-a72e-1c0ebcbd1341",
                            CreatedAt = new DateTime(2024, 1, 18, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.mohamed@example.com",
                            EmailConfirmed = false,
                            ImageUrl = "https://i.pravatar.cc/150?img=45",
                            LockoutEnabled = false,
                            Name = "Fatima Mohamed",
                            PasswordHash = "AQAAAAEAACcQAAAAEH8zQK",
                            PhoneNumber = "01123456789",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AmenityProperty", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("amenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IjarifySystemDAL.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("propertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Booking", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Property", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IjarifySystemDAL.Entities.User", "user")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("user");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Favourite", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Property", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IjarifySystemDAL.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Inquiry", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Property", "Property")
                        .WithMany("PropertyInquiries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IjarifySystemDAL.Entities.User", "User")
                        .WithMany("UserInquiries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Offer", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Property", "Property")
                        .WithMany("PropertyOffers")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Property", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Location", "Location")
                        .WithMany("Properties")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IjarifySystemDAL.Entities.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.PropertyImages", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Review", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.Property", "property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IjarifySystemDAL.Entities.User", "user")
                        .WithMany("reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("property");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IjarifySystemDAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("IjarifySystemDAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Location", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.Property", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("PropertyImages");

                    b.Navigation("PropertyInquiries");

                    b.Navigation("PropertyOffers");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("IjarifySystemDAL.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Properties");

                    b.Navigation("UserInquiries");

                    b.Navigation("reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
